### ISSUE TITLE
Sorting deltas

### ISSUE THREAD

**Issue by Rupke75** [Geodan/cow#184]
The deltas aren't sorted in any way.

When a peer has changed data during its offline period and other (online) peers have altered data for that item too in that period the delta of the offline peer is added to the end of the array of deltas when that peer comes online after the changes of the online peers.
That way the change of the offline peer will be seen as the last delta, which is not expected behaviour.

By sorting the delta array based on the timestamp this issue will be resolved.

**Comment by tomvantilburg** [comment]
Probably fixed by default sorting deltas by timestamp. Oldest comes last.

**Comment by tomvantilburg** [comment]
Seems good
